image:
  file: .gitpod.Dockerfile
  
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script'
    command: echo 'start script'
    openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3306
    onOpen: open-preview

  - port: 33060
    onOpen: open-preview
